### ISSUE TITLE
Runtime error: Duplicate method name & signature

### ISSUE THREAD

**Issue by ctongfei** [miniboxing/miniboxing-plugin#192]
``` scala
trait Monoid[@miniboxed X] {
  def id: X
  def op(x: X, y: X): X
}

trait EndofunctionSpace[@miniboxed X] {
  def asMonoidWithCompose: Monoid[X => X] = new Monoid[X => X] {
    def id = (x: X) => x
    def op(f: X => X, g: X => X) = (x: X) => f(g(x))
  }
}

object Test extends App {

  val fs = new EndofunctionSpace[Double] {}
  val m = fs.asMonoidWithCompose
  val f = math.sin _
  val g = math.asin _
  val fg = m.op(f, g)
  val fg1 = fg(1)
  print(fg1)
}
```

Runtime exception thrown:

```
Exception in thread "main" java.lang.ClassFormatError: Duplicate method name&signature in class file EndofunctionSpace_D$$anon$2
    at java.lang.ClassLoader.defineClass1(Native Method)
...
```

This is apparently an error of the miniboxing process.

**Comment by VladUreche** [comment]
@ctongfei, thank you for the report and sorry for not testing the entire use case. I am travelling now, with limited internet access, so please expect delays.

On a quick inspection, the duplicate method is created in the erasure phase, which is outside the control of the miniboxing plugin. I will try to isolate exactly why it gets generated, but this may take a while.

**Comment by VladUreche** [comment]
I'm starting to understand the root cause of the problem but I don't know what's the best way to fix it (yet).

**Comment by VladUreche** [comment]
Tried a naive fix => not working, as expected :(

**Comment by VladUreche** [comment]
Still working on this, I made some progress during the flight, but there are multiple issues at play and fixing one breaks another. So I'm still looking for a proper solution, that doesn't break everything else.

**Comment by ctongfei** [comment]
Thank you for your effort. Miniboxing is really something I'd like to use in my projects.

**Comment by VladUreche** [comment]
@ctongfei, thanks for the bug report, it uncovered a big issue in the way bridge methods were being generated. The latest commit should handle this correctly, just use `sbt update` before re-compiling.

Btw, I added [your test case](https://github.com/miniboxing/miniboxing-plugin/blob/wip/tests/correctness/resources/miniboxing/tests/compile/gh-bug-192-full.scala) to [the test suite](https://github.com/miniboxing/miniboxing-plugin/blob/wip/tests/correctness/resources/miniboxing/tests/compile) and it works fine now.
