### ISSUE TITLE
Double definition

### ISSUE THREAD

**Issue by ctongfei** [miniboxing/miniboxing-plugin#193]
``` scala
trait Group[@miniboxed X] {
  def add(x: X, y: X): X
  def zero: X
  def neg(x: X): X
  def sub(x: X, y: X) = add(x, neg(y))
}
trait Ring[@miniboxed X] extends Group[X] {
  def mul(x: X, y: X): X
  def one: X
  def negOne = neg(one)
}
trait Module[V, @miniboxed R] extends Group[V] {
  def ringOfScalar: Ring[R]
  def scale(k: R, x: V): V
  def neg(x: V): V = scale(ringOfScalar.negOne, x)
}
trait FunctionSpace[X, Y, @miniboxed R] extends Module[X => Y, R] {
  def moduleOfCodomain: Module[Y, R]
  def scale(a: R, f: X => Y) = (x: X) => moduleOfCodomain.scale(a, f(x))
  override def neg(f: X => Y) = (x: X) => moduleOfCodomain.neg(f(x))
  def zero = (x: X) => moduleOfCodomain.zero
  def add(f: X => Y, g: X => Y) = (x: X) => moduleOfCodomain.add(f(x), g(x))
  override def sub(f: X => Y, g: X => Y) = (x: X) => moduleOfCodomain.sub(f(x), g(x))
}
```

This does not compile. Compile error:

```
Error:(26, 16) double definition:
override def neg(x: X => Y): X => Y at line 26 and
override def neg(x: X => Y): X => Y at line 26
have same type
  override def neg(f: X => Y) = (x: X) => moduleOfCodomain.neg(f(x))
               ^
```

Sorry for spamming you with issues these days :-)

**Comment by ctongfei** [comment]
This is more interesting: having all @miniboxed annotations removed, this error still persists. However, if I remove the miniboxing compiler plugin, it worked well.

**Comment by VladUreche** [comment]
Thanks for the report @ctongfei! That's expected since your code uses many functions, and [they are transformed automatically by the miniboxing plugin](http://scala-miniboxing.org/example_functions.html). Btw, you're the first _serious_ user of the function representation transformation, so you're bumping into all the issues. :| Nevertheless, we'll resolve them one by one until you can compile your application successfully.

I will look into the problem shortly.

**Comment by VladUreche** [comment]
Further reduced to:

``` scala
$ cat gh-bug-193.scala 
trait Group[X] {
  def neg(x: X): X
}
trait Module[V, @miniboxed R] extends Group[V] {
  def neg(x: V): V = ???
}
trait FunctionSpace[X, Y, @miniboxed R] extends Module[X => Y, R] {
  override def neg(f: X => Y): X => Y = ???
}

$ mb-scalac gh-bug-193.scala 
gh-bug-193.scala:8: error: double definition:
override def neg(x: X => Y): X => Y at line 8 and
override def neg(x: X => Y): X => Y at line 8
have same type
  override def neg(f: X => Y): X => Y = ???
               ^
one error found
```

**Comment by VladUreche** [comment]
Okay, I've isolated the error, now looking into how to fix it.

**Comment by VladUreche** [comment]
Should work now, thanks for the report @ctongfei!

**Comment by ctongfei** [comment]
not working. perhaps you haven't pulished it to sonatype?

**Comment by VladUreche** [comment]
Perhaps it took some time to build and publish on travis. I will check in
the evening, right now I don't have my computer.

**Comment by VladUreche** [comment]
@ctongfei, please check again now (do an `sbt update`) -- you were right, it did not push the latest version to sonatype, although the Travis build did succeed: https://travis-ci.org/miniboxing/miniboxing-plugin/builds/53368873. I published it by hand now...

**Comment by VladUreche** [comment]
Hi @ctongfei, did this work for you? Also, if you encounter any more bugs or have questions don't hesitate to ping me.

**Comment by ctongfei** [comment]
This worked but i found another bug which i haven't got time to properly isolate it (compiler says multiple annotation @mbFunction @mbFunction @mbFunction). I'm busy doing my research stuff so i'm not working on Scala this week. Thank you!

**Comment by VladUreche** [comment]
Thanks and the best of luck on your research!
