### ISSUE TITLE
Add link to the MbArray documentation in warning content which suggests using MbArray instead of Array

### ISSUE THREAD

**Issue by milosstojanovic** [miniboxing/miniboxing-plugin#207]
Current warning content: 
Use MbArray instead of Array and benefit from miniboxing specialization

Introduced here: https://github.com/miniboxing/miniboxing-plugin/pull/206

**Comment by VladUreche** [comment]
@milosstojanovic, can I assign this one to you?

**Comment by VladUreche** [comment]
Fixed by @milosstojanovic in PR #216.
