### ISSUE TITLE
Wrong Least Square Linear Regression benchmark for RRBVector

### ISSUE THREAD

**Issue by milosstojanovic** [miniboxing/miniboxing-plugin#232]

**Comment by VladUreche** [comment]
LGTM! Thanks @milosstojanovic!

**Comment by VladUreche** [comment]
Hmm -- this is an issue with an attached commit, but not a PR -- when you file the PR, feel free to merge it directly :)

**Comment by VladUreche** [comment]
:+1:

**Comment by milosstojanovic** [comment]
Link to correct benchmarks: https://github.com/milosstojanovic/mb-benchmarks
