### ISSUE TITLE
Upgrade Scala to 2.10.6

### ISSUE THREAD

**Issue by alexandru** [miniboxing/miniboxing-plugin#247]
Hey,

Can the Scala version be updated to the latest `2.10.6`?

**Comment by VladUreche** [comment]
Hi @alexandru! 
Sure. But do you use miniboxing on 2.10? I was actually planning to deprecate 2.10 support :-s

**Comment by alexandru** [comment]
I don't have any requirements for 2.10, but I noticed 2.10.5 and in my projects I migrated to the latest 2.10.6. I guess supporting 2.10.x is a burden given that 2.12 is coming.

**Comment by VladUreche** [comment]
Yes, but 2.12 will need its own branch anyway (so I transform `MiniboxedFunctions` into functional interfaces), so maybe it's not so bad to support 2.{10,11} on this branch. Tests are running now, will push the patch in a few minutes. Thanks for the ping!

**Comment by alexandru** [comment]
That was fast :-)

**Comment by VladUreche** [comment]
Luckily I didn't hit any roadblocks, tests went fine. :+1: for the source/binary compatibility of Scala!
