### ISSUE TITLE
Build: use the scalaVersion setting everywhere

### ISSUE THREAD

**Issue by adriaanm** [miniboxing/miniboxing-plugin#57]
I believe `val scalaVer = ...` is a code smell in SBT (as seen in https://github.com/miniboxing/miniboxing-plugin/blob/master/project/Build.scala#L55)

Use `scalaVersion.value` instead -- the `.value` macro works wherever you're defining settings -- see `Def.task` if you need to use it somewhere else.

You also shouldn't have to set the `scalaBinaryVersion` directly.

Hardwiring values of dependencies makes it hard to automate integration builds. All settings should be settable from the command line using e.g., `set scalaVersion := '...'`. We also introduced settings for all versions of dependencies so we can set them to -SNAPSHOT for integration builds. For example: https://github.com/rickynils/scalacheck/blob/master/project/versions.scala

**Comment by adriaanm** [comment]
(All this is assuming SBT 0.13 of course.)

**Comment by VladUreche** [comment]
Thanks @adriaanm! Yes, I just upgraded to sbt 0.13 a few days ago.
