### ISSUE TITLE
Use optimized coercions

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#63]
the plugin does not rewire to shortcuts:

```
minibox2box(..., INT) => minibox2int(...)
```

(moved from https://github.com/miniboxing/miniboxing-plugin/wiki/Details-|-Known-Limitations)

**Comment by VladUreche** [comment]
With miniboxing/erasure, this should be pretty easy to do.

**Comment by VladUreche** [comment]
Not until I benchmark the two implementations head to head :)

**Comment by MelodyLucid** [comment]
Have a look at this https://github.com/MelodyLucid/freezing-ironman/commit/b1ce1803b4a0be90581aa9ff7dfacb20e6dda783

**Comment by VladUreche** [comment]
Simple testcase for this bug:

```
sun@sun-laptop:~/workspace/dev/miniboxing-plugin/sandbox(wip)$ cat test.scala
class C[@miniboxed T] {
  def foo(t: T): T = t
}

class D extends C[Int] {
  override def foo(t: Int): Int = t + 1
}
sun@sun-laptop:~/workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac -Xprint:minibox-spec test.scala
[[syntax trees at end of              minibox-spec]] // test.scala
package <empty> {
  abstract trait C[@miniboxed T >: Nothing <: Any] extends Object {
    def foo(t: T): T;
    def foo_J(T_TypeTag: Byte, t: Long): Long
  };
  class D extends C_J[Int] {
    def <init>(): D = {
      D.super.<init>(5);
      ()
    };
    override def foo(t: Int): Int = MiniboxConversions.this.minibox2box[Int](D.this.foo_J(5, MiniboxConversions.this.box2minibox_tt[Int](t, 5)), 5);
    override def foo_J(T_TypeTag: Byte, t: Long): Long = MiniboxConversions.this.box2minibox_tt[Int](MiniboxConversions.this.minibox2box[Int](t, 5).+(1), 5)
  };
  class C_J[Tsp >: Nothing <: Any] extends Object with C[Tsp] {
    def <init>(C_J|T_TypeTag: Byte): C_J[Tsp] = {
      C_J.super.<init>();
      ()
    };
    def foo(t: Tsp): Tsp = MiniboxConversions.this.minibox2box[Tsp](C_J.this.foo_J(C_J.this.C_J|T_TypeTag, MiniboxConversions.this.box2minibox_tt[Tsp](t, C_J.this.C_J|T_TypeTag)), C_J.this.C_J|T_TypeTag);
    def foo_J(T_TypeTag: Byte, t: Long): Long = t;
    <paramaccessor> private[this] val C_J|T_TypeTag: Byte = _
  };
  class C_L[Tsp >: Nothing <: Any] extends Object with C[Tsp] {
    def <init>(): C_L[Tsp] = {
      C_L.super.<init>();
      ()
    };
    def foo(t: Tsp): Tsp = t;
    def foo_J(T_TypeTag: Byte, t: Long): Long = MiniboxConversions.this.box2minibox_tt[Tsp](C_L.this.foo(MiniboxConversions.this.minibox2box[Tsp](t, T_TypeTag)), T_TypeTag)
  }
}
```

whenever you see `MiniboxConversions.this.minibox2box[Int]` or `MiniboxConversions.this.box2minibox[Int]`, that's suboptimal and should be replaced by
`MiniboxConversions.this.MiniboxToInt` or `MiniboxConversions.this.IntToMinibox`

For reference:
- `minibox2box`: https://github.com/miniboxing/miniboxing-plugin/blob/wip/components/runtime/src/miniboxing/runtime/MiniboxConversions.scala#L60-L75
- `box2minibox_tt`: https://github.com/miniboxing/miniboxing-plugin/blob/wip/components/runtime/src/miniboxing/runtime/MiniboxConversions.scala#L97-L108
- optimized variants: https://github.com/miniboxing/miniboxing-plugin/blob/wip/components/runtime/src/miniboxing/runtime/MiniboxConversions.scala#L18-L45

**Comment by VladUreche** [comment]
GSOC challenge: https://gist.github.com/VladUreche/9609650
